### ISSUE TITLE
ssl handshake failure

### ISSUE THREAD

**Issue by Playfrog4u** [janrueth/SiriServerCore#10]
WARNING [('SSL routines', 'SSL3_READ_BYTES', 'ssl handshake failure')]
is the error i get alot. Any ideas

**Comment by janrueth** [comment]
Did you generate certificates? Seems like you have a mismath of the ca.pem and you server.crt

**Comment by Playfrog4u** [comment]
Yes. I fixed it. Thank you.

**Comment by janrueth** [comment]
Note, from now on the server can generate certificates on his own, there is no need for external scripts...

**Comment by Aaryans** [comment]
What does this error mean ?

$ python ./siriserver.py
Warning: Your system does not support epoll
         Will to use simple poll
INFO Starting server on port 4443
Traceback (most recent call last):
  File "./siriserver.py", line 110, in <module>
    main()
  File "./siriserver.py", line 105, in main
    reactor.listenSSL(options.port, SiriFactory(), ssl.DefaultOpenSSLContextFact
ory('keys/server.key', 'keys/server.crt'))
  File "/usr/lib/python2.6/site-packages/Twisted-12.0.0-py2.6-cygwin-1.7.10-i686
.egg/twisted/internet/ssl.py", line 68, in **init**
    self.cacheContext()
  File "/usr/lib/python2.6/site-packages/Twisted-12.0.0-py2.6-cygwin-1.7.10-i686
.egg/twisted/internet/ssl.py", line 77, in cacheContext
    ctx.use_certificate_file(self.certificateFileName)
OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('
BIO routines', 'FILE_CTRL', 'system lib'), ('SSL routines', 'SSL_CTX_use_certifi
cate_file', 'system lib')]

**Comment by janrueth** [comment]
You got not certificates installed, use the newest version, cert generation is included
