### ISSUE TITLE
Plugin development

### ISSUE THREAD

**Issue by macuseri686** [janrueth/SiriServerCore#105]
This is an awesome project you've got going on here. I personally run my own server with some heavily tweaked plugins. On setting up said server, I had great difficulty finding plugins etc as they are not all in one place. Also, there really is no "forum" anymore like there was before for plugin creators to participate in. 

Is there a reason for this or should someone launch a forum.

-macuseri686

BTW my website is http://tmobile.ignorelist.com:81
I have 3 public servers

**Comment by weinzach** [comment]
Well we have had forums but people kept spamming them if theres a demand i can try to start up a new one with a Spam Blocker...

**Comment by macuseri686** [comment]
Yeah, gotta hate those spammers :( . All you really need to do though is just setup a captcha for registation on the forum. ;)

**Comment by macuseri686** [comment]
OK, I've launched a forum at http://tmobile.ignorelist.com:81/forum/

Theres a section for plugins and development ;)
