### ISSUE TITLE
Mac OS X Dictation Issues.

### ISSUE THREAD

**Issue by weinzach** [janrueth/SiriServerCore#107]
So I saw the latest commit on SiriServerCore and I am interested in testing the dictation on my server for the fun of it. Just asking for anyone who got it working on Mac OS X how did you get the Mac to connect to your google API server?

**Comment by janrueth** [comment]
Thats fairly easy, have a look at ~/Library/Preferences/com.apple.assistant.plist. You can convert the file with plutil -convert xml1 to xml and then add witin the center dict: <key>hostname</key
<string>https://yourip:port</string> 

Remember to install the ca certificate for the server

**Comment by janrueth** [comment]
Damn iphone
    <key>hostname</key>
    <string>https://host:port</string>

**Comment by janrueth** [comment]
Damn can't format it correctly, first is a key second is a stri g, you should get it from the rest of the file

**Comment by janrueth** [comment]
noch from my mac, a small example

`blofeld:~ jan$ cat ~/Library/Preferences/com.apple.assistant.plist`
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Accounts</key>
    <dict>
        <key>521A9C00-5B5A-4E43-AB9C-6B72521687D1</key>
        <dict>
            <key>Hostname</key>
            <string>https://blofeld.local</string>
        </dict>
    </dict>
    <key>Session Language</key>
    <string>de-DE</string>
</dict>
</plist>`

**Comment by weinzach** [comment]
Cool thanks @Eichhoernchen works flawlessly now we just need a preference panel so users could change the servers easier.

**Comment by janrueth** [comment]
I might have a look into that, never programmed for os x

**Comment by janrueth** [comment]
Fairly easy, have fun with it, did not really test everything out

http://download.siri-server.com/SiriPrefsForOSX.prefPane.zip
