### ISSUE TITLE
Remote execution

### ISSUE THREAD

**Issue by macuseri686** [janrueth/SiriServerCore#108]
I'm writing a plugin that will execute an SH script on the iPhone.

For instance if i say "open an ssh tunnel", I want the server to send the command "ssh username@ip" to the iPhone to execute. Is this even possible to do? I could have the server ssh into the iphone to send the command, but that seems rather redundant.

**Comment by janrueth** [comment]
not possible without modification of siri

You can however ssh into the iphone and execute the script from the server

**Comment by macuseri686** [comment]
Thnx ;) will see about that.
