### ISSUE TITLE
epoll .. issue

### ISSUE THREAD

**Issue by ghost** [janrueth/SiriServerCore#11]
can anybody help me i get always this error : 

Warning: Your system does not support epoll
Will to use simple poll

**Comment by janrueth** [comment]
this is a warning... epoll is a sophisticated mechanism on linux to run the server, you are probably running the server not on linux, so the system tries to use the next best mechanism, which is poll. If poll is not available (windows...) it will use simple selects (last one is comparable to what asyncore did in the old core)

So don't worry, this is no error just information that it could not find an epoll interface
