### ISSUE TITLE
All responses in German

### ISSUE THREAD

**Issue by Matchstic** [janrueth/SiriServerCore#114]
Well, the server itself works great! However, every reply I receive from the server on the device is in German, no matter what the locale and language setting is. Annoyingly, it isn't isolated to one device - every device that connects has the same issue. Some help to resolve this would be greatly appreciated!

![IMG_0165](https://f.cloud.github.com/assets/2507144/144009/bbe0ce3c-73e2-11e2-9eea-be2b9caa43a1.PNG)

**Comment by JulianAnthes** [comment]
Seems to me, this error is caused by a plugin. The SiriServerCore has no error message like that (imho). Maybe you should deactivate all plugins and reactivate one by one. Also searching the plugins code for "Sorry kannst du das wiederholen, bitte?" should help you solving this issue.

**Comment by Matchstic** [comment]
@dschu-lab Cheers, that was the issue, turns out the backend for my chatbot plugin was down
