### ISSUE TITLE
OS X 10.8.2 Dictation issue

### ISSUE THREAD

**Issue by Baton72** [janrueth/SiriServerCore#115]
Cannot make SiriServer to work with OS X 10.8.2.

My com.apple.assistant.plist looks like:
![Screen Shot 2013-03-08 at 17 05 59](https://f.cloud.github.com/assets/3604634/236275/33c8b39a-87e0-11e2-8a30-392f7b839e25.png)

iPhone4 with Spire works with no problems, but for MAC SiriServer says:

INFO Starting server on port 4443
INFO Loading Session Certificates
INFO Setting Up Database
INFO Connection to Database
INFO Loading Plugin Framework
INFO Server is running and listening for connections
INFO New connection from 192.168.0.3 on port 65449
INFO Currently 1 clients connected
WARNING SSL related error
WARNING [('SSL routines', 'SSL3_READ_BYTES', 'ssl handshake failure')]
INFO Currently 0 clients connected
INFO New connection from 192.168.0.3 on port 65450
INFO Currently 1 clients connected
WARNING SSL related error
WARNING [('SSL routines', 'SSL3_READ_BYTES', 'ssl handshake failure')]
INFO Currently 0 clients connected

**Comment by weinzach** [comment]
You probably have to trust the certificate of your server like you did on your iphone.

**Comment by Baton72** [comment]
Yeah! You're right! Found the manual, added ca.pem according it and now dictation is working! Many thanks!

The manual:
    Open the Keychain Access application.
    Select the Certificates category.
    Click the plus icon (+) button on the lower toolbar, then find and select the certificate.
    Select the System keychain, then click Open. You can also select the System keychain, then drag and drop the certificate file into the list.
    Right-click the certificate and select Get Info.
    A certificate information window appears.
    Expand the Trust category.
    In the When using this certificate drop-down list, select Always Trust.
    Close the certificate information window.
    Type your administrator password to confirm your changes.

**Comment by RonaldKonijnenburg** [comment]
Just as a matter of interest. What are you using this for? What do you let siri do on your mac what cannot be done with the standard speech stuff?

**Comment by Baton72** [comment]
Just one simple thing - Russian language support! :)
