### ISSUE TITLE
Connections not decreasing....

### ISSUE THREAD

**Issue by jimmykane** [janrueth/SiriServerCore#12]
I might be wrong but using the Core for one day on the public server i noticed that connection count is not dropping right. 
It always increases, drops sometimes but the actual cuncurrent count is wrong. 

Eg reports 70 connections while 10-20 may be active.

**Comment by snxraven** [comment]
i was going to post about this u beat me haha

**Comment by jimmykane** [comment]
I have seen in the code the method that the connections are counted. All similar code snippets on the web recomended this method that you use and seems theoriticaly logical to work. But I am not expirenced on this thus cannot tell for sure. 
Mabe we need to monitor the connectionFailure method or list active sockets

**Comment by janrueth** [comment]
Actually it monitors the connectionLost method, I think the count does not decrease because when siri finishes a single speech request and is dismissed on the device it does not automatically close the connection and thus stays alive for some more time

**Comment by jimmykane** [comment]
Ok. So lets set a better timeout ?

**Comment by janrueth** [comment]
Hm... don't know if that is a problem anyways.. but yeah, be could say... no ping within 10 sec.. DIE

**Comment by jimmykane** [comment]
no 10 secs is little. More like one minute is ok.

**Comment by janrueth** [comment]
ah the ping is very constant.. you actually get a ping very second... or another packet... so 10 sec would be fine... but we could make that adjustable...

However... beer is currently holding me back from development

**Comment by jimmykane** [comment]
Go for beer! Is what I love too! And you are lucky because (i suppose you live in Germany) you live in the Queen country of Beer! 

Don't worry I am learning python as fast as i can so i can contribute more.

**Comment by janrueth** [comment]
Thx... Friday evening .... germany... beer... ...beer.... ahh waiit..... no... beer again... beer... so.... as far as I know... I had a byte ... or.. at least a nibble... http://www.bitburger.com/

**Comment by janrueth** [comment]
Should now be implemented, every 20 seconds it is checked if the last ping was more than 10 seconds ago... this max a maximum stall connection timeout of 30 seconds
