### ISSUE TITLE
Lots of people cant connect :(

### ISSUE THREAD

**Issue by Playfrog4u** [janrueth/SiriServerCore#17]
WARNING SSL related error
WARNING [('SSL routines', 'SSL3_READ_BYTES', 'ssl handshake failure')]
 is showing up alot and they have new cert.
Also the HELLO error due to http:// when they have https://

Any clues.

**Comment by Playfrog4u** [comment]
I got latest pull

**Comment by jimmykane** [comment]
SSL ERROR!

**Comment by janrueth** [comment]
Certs either not in place or wrong!

**Comment by janrueth** [comment]
They also must delete the old cert ;)
