### ISSUE TITLE
ssl cert generation error

### ISSUE THREAD

**Issue by cytec** [janrueth/SiriServerCore#21]
/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/twisted/internet/_sslverify.py:5: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import itertools, md5
I could not find valid certificates. I will now guide you through the process of creating some.
I will create a Certification Authority (CA) first
Workstation1:SiriServerCore workstation$ Traceback (most recent call last):
  File "SiriServer.py", line 273, in <module>
    main()
  File "SiriServer.py", line 250, in main
    create_self_signed_cert()
  File "SiriServer.py", line 108, in create_self_signed_cert
    extensions.append(crypto.X509Extension("basicConstraints", critical=False, value="CA:TRUE"))
TypeError: X509Extension() takes no keyword arguments

**Comment by cytec** [comment]
nevermind, upgraded twisted and pyOpenSSL ... works now :)

**Comment by cytec** [comment]
but it seems like there isnt a mapObjects file anymore?

Traceback (most recent call last):
  File "/volume1/Private/SiriServerCore/PluginManager.py", line 30, in load_plugins
    **import**(pluginPath+"."+line,  globals(), locals(), [], -1)
  File "/volume1/Private/SiriServerCore/plugins/whereAmI.py", line 15, in <module>
    from siriObjects.mapObjects import SiriLocation, SiriMapItem, SiriMapItemSnippet
ImportError: No module named mapObjects

**Comment by janrueth** [comment]
yes... got removed, it is redundant, Location was already available in systemObjects and the other in localSearchObjects...

mapObjects did not reflect inner siri structure therefore was removed
