### ISSUE TITLE
Discussion on plugin coding. 

### ISSUE THREAD

**Issue by jimmykane** [janrueth/SiriServerCore#24]
Most of the plugins do not use a lot of ask - reply from user. This is a simple chatbot plugin. http://pastebin.com/SDZgS02B

It Loops on asking the user for something and sends that to a bot service and then asks again etc etc until it hears stop. 
Then exits. 

The problem is that if she wont hear stop then the plugin freezes the server and needs a kill -9 

In my opinion is that a finish signal is not sent. But I am not a plugins expert and can't find any docu of eg proper completion of ask() function. This is where i think the problem comes. 

It's simple code and i think it's worth the while to even explain a bit about the plugins ask etc etc

**Comment by cytec** [comment]
yeah i got you, there should be a "user canceled request" thing ... im pretty shure ive seen that in the "logs" a while ago...
maybe its possible to pass that to the plugin or cancel a running plugin when the user "exits" siri or cancels the request?

**Comment by janrueth** [comment]
the thing is, we cannot kill threads. If a plugin is processing we cannot kill it. However a next request should not be handled by the plugin anymore. There is a check that it can only receive answers which have the same refId than the ask request it sent.

I think I will add that we can kill a plugin if it is waiting for reply from the user... that would be possible, however I think it is not possible to kill the thread when it is processing.

**Comment by boeaja** [comment]
I m the one who made ask for chatbot, first code from paradox not using ask, i want to make more like conversation so i add ask and looping it until it stop, maybe i was wrong implement the ask code... I dont read full code of ask.. Some time it make server crash or cant be stop if chat unfinished ... 
i m not a python expert.. 
Maybe i was wrong put that code..

**Comment by jimmykane** [comment]
Ok but the thread should exit after plugin killing. 
Right?

**Comment by janrueth** [comment]
year, but we cannot force it, I will implement something to make it exit if it waits for an answer, but I cannot kill its processing. But I will make it that it cannot send something

**Comment by janrueth** [comment]
I just pushed a commit that allows the plugin to abort a current plugin run
