### ISSUE TITLE
self.ask responces not being processed

### ISSUE THREAD

**Issue by gavros** [janrueth/SiriServerCore#26]
Upgraded to the new core and all seems to be working fine except for scripts calling any self.ask functions.
It seems that any information processed after a self.ask will not continue running within the script. It seems that its trying a new query instead of appending to the first request.

Examples of this would be selecting a number when calling a contact or any other script where you would have to provide a verbal response. In the example above (when making a phone call selection, manually selecting it works).  

Any ideas?

**Comment by gavros** [comment]
This is what I see in my terminal session (just noticed that the plugin mysteriously aborted line 3)
1. INFO Sending flac to google for recognition
2. INFO Best matching result: "Call Vicki Vail" with a confidence of 62.48%
3. INFO Plugin stopped executing with reason: 'Plugin run was aborted'
4. INFO Sending flac to google for recognition
5. INFO Best matching result: "Work" with a confidence of 95.47%
6. ae8206713e34cb2e

In line 5 (since the plugin was aborted it trying to find Work, so the chatbot picks up from here.

**Comment by cytec** [comment]
seems like the plugin gets aborted instead of waiting for an answer to process... this may be an error with the latest commit from Eichhoernchen, where he added support to abort plugins...

**Comment by gavros** [comment]
Could be the cause. As I mentioned in the forum, the last files that were updated are:

plugin.py - yesterday (3/14)
SiriProtocolHandler.py - yesterday (3/14) 
and
SiriCore.py - 4 days ago

If someone has older versions of these files I can try troubleshooting and see which one may have caused the issue. Can someone post them somewhere so I can give it a go?

**Comment by gavros** [comment]
Ok the problem seems to be the latest SiriProtocolHandler.py (dated 3/14/2012).
I used the SiriProtocolHandler.py posted back on March 7th and problem was resolved.

Please look into the above script(s). If anyone is looking for a workaround, please use the older version of SiriProtocolHandler.py dated back on the 8th or until a resolution is found.

I'll post a writeup in the forum as well.

**Comment by janrueth** [comment]
Might that I bricked that, I must take a second look at how the request response game is played...

**Comment by gavros** [comment]
Thanks. This is the version I used:
now sharing sqlite db connection between connections, better startup 

https://github.com/Eichhoernchen/SiriServerCore/blob/10763b91e4cc970cf42fbb6ddcb8c7c3d02c90d6/SiriProtocolHandler.py

**Comment by janrueth** [comment]
I do remember now, if one does asks, the iphone sends a cancel request after each said text... I gotta figure out when CancelRequest is sent and when (I think there is a rollback request) one should really kill the plugin

**Comment by janrueth** [comment]
This https://github.com/Eichhoernchen/SiriServerCore/commit/778ce65fbedd00fd0ef786860b378762726d5d31 should have fixed the issue

**Comment by weinzach** [comment]
Hey gavros. Just asking how did you get the chatbot to pick up on the Work command? It would help me a lot. thanks..
