### ISSUE TITLE
Email url

### ISSUE THREAD

**Issue by WebScript** [janrueth/SiriServerCore#27]
Hi!
Can somebody tell me how to generate URL like apple servers while sending email? In email it needs reference id in url.

**Comment by janrueth** [comment]
Maybe if you tell us how they look 0.o got no 4S for testing...

**Comment by WebScript** [comment]
Or how can I generate this url? It is used in reminders.  amos://48702C78-CF92-46E0-8575-BD2F4781646A

**Comment by janrueth** [comment]
I guess you are talking about:  `class EmailEmail(DomainObject):`

As it is a DomainObject I suppose you need to create one via `class DomainObjectCreate(ClientBoundCommand):`
which will probably give you the referenceId, can you provide 4S dumps for email?

**Comment by WebScript** [comment]
No, I can't. Dump for reminders is here:
http://pastie.org/private/soxctvkvmbscyrveix8ca

**Comment by janrueth** [comment]
exactly as I said... have a look at systemObjects for DomainObjectCreate and at emailObjects for EmailEmail

**Comment by WebScript** [comment]
Ok, I will look at it.

**Comment by WebScript** [comment]
I don't know how to use it. Can you give some example?

**Comment by janrueth** [comment]
No, have never used it

**Comment by janrueth** [comment]
I think you just use DomainObjectCreate, DomainObjectCreateCompleted should come back with the url of the object

you can later retrieve it via DomainObjectRetrieve, which will trigger a DomainObjectRetrieveCompleted with the object you requested.

You can update a DomainObject via DomainObjectUpdate, which triggers a DomainObjectUpdateCompleted on success.

Everytime you address an DomainObject via the class DomainObject, you just set the identifier member var to the url.

The *completed objects are not yet implemented the rest resides in siriObjects.systemObjects

**Comment by danzatt** [comment]
I'm working on email plugin. First you must create domain object and then wait for answer (It'll send identifier what you want). Here's code :
class mail(Plugin):

```
@register("en-US", ".*mail.*")  
def mail(self, speech, language):
            email = EmailEmail() # create EmailEmail object
            email.subject = "test" # you can set other parameters (such as message, to email, ...)
            EmailDomain = DomainObjectCreate(self.refId, email)    #create DomainObject                
            answer = self.getResponseForRequest(EmailDomain) # get response
            if ObjectIsCommand(answer, DomainObjectCreateCompleted): #check if response is DomainObjectCreateCompleted
                   identifier = DomainObjectCreateCompleted(answer)
                   print "\n\nIDENTIFIER : ", identifier.identifier # if yes, print identifier
             else:
                   raise StopPluginExecution("Unknown response: {0}".format(answer)) # else, something went wrong
```

But I didn't find DomainObjectCreateCompleted, so I've created it (add this to systemObjects):

class DomainObjectCreateCompleted(ServerBoundCommand):
    classIdentifier = "DomainObjectCreateCompleted"
    groupIdentifier = "com.apple.ace.system"

```
def __init__(self, plist):
    self.identifier = None #string
    super(DomainObjectCreateCompleted, self).__init__(plist)
```

@Eichhoernchen you can add this to repo 
Hope I've helped.

**Comment by janrueth** [comment]
Very nice code, will add the createCompleted!

**Comment by danzatt** [comment]
Thanks, I've edited my post becouse there was mistake :
EmailDomain = DomainObjectCreate(self.refId)
EmailDomain.obj = email

Don't work, but this yes :

EmailDomain = DomainObjectCreate(self.refId, email)

But now I have another issue, it send this plist :

{'properties': {'callbacks': [], 'object': {'group': 'Email', 'class': 'Object', 'properties': {'identifier': 'com.apple.ace.email', 'type': 'New', 'subject': 'test'}}}, 'aceId': '333FB62D-F4EF-4BD8-AE5F-85B1C7252851', 'group': 'com.apple.ace.system', 'refId': '0238550B-ACC0-4AB4-A1CB-88B85419965F', 'class': 'DomainObjectCreate'}

Original plist from 4S looks like : 

{"class"=>"DomainObjectCreate",
 "properties"=>
  {"object"=>
    {"class"=>"Email",
     "properties"=>
      {"type"=>"New",
       "subject"=>"test",
       },
     "group"=>"com.apple.ace.email"}},
 "aceId"=>"271ea43f-8171-4394-81ab-d51765849b59",
 "refId"=>"23EAEE37-80C4-4B8D-9486-E4EEDFC4A8EE",
 "group"=>"com.apple.ace.system"}

**Comment by WebScript** [comment]
Thanks Paradox.
Ďakujem Paradox. Trošku to upravím a vylepším a snáď to bude pasovať aj do mojho serveru.

Odoslané z iPhonu

Dňa 17.3.2012, o 8:22, P4r4doXreply@reply.github.com napísal:

**Comment by janrueth** [comment]
So the group and class are wrong okay, I'll have a look into that

**Comment by janrueth** [comment]
Should be fixed, also it is not:

```
 EmailDomain = DomainObjectCreate(self.refId)
 EmailDomain.obj = email
```

but

```
 EmailDomain = DomainObjectCreate(self.refId)
 EmailDomain.object = email
```

actually it is called object, but we cannot use object in the parameters as it is reserved as far as my editor tells me, so I called it obj there. Usually the contructor parameters are called like the member vars but you should always make sure which member vars are available by looking at the constructor

**Comment by WebScript** [comment]
Now it only sends this:
{'aceId': 'DE2A166F-8514-4480-AE13-33DF6E4330C8',
 'class': 'DomainObjectCreate',
 'group': 'com.apple.ace.system',
 'properties': {'callbacks': [],
                'object': {'class': 'Object',
                           'group': 'com.apple.ace.email',
                           'properties': {'subject': 'test'}}},
 'refId': '9DDA6808-142D-4E31-87BD-A54F48B4144D'}

and 2 seconds iPhone is working and then nothing is returned to server. I can't see stopped plugin or identifier.

**Comment by janrueth** [comment]
thats odd, there should not be class: object but class: email, I'll recheck that

**Comment by janrueth** [comment]
Here it does work:

```
from siriObjects.systemObjects import DomainObjectCreate
from siriObjects.emailObjects import EmailEmail
x = DomainObjectCreate("HERE COMES THE REF ID")
x.object = EmailEmail()
print x.to_plist()

{'properties': {'callbacks': [], 'object': {'group': 'com.apple.ace.email', 'class': 'Email', 'properties': {}}}, 'aceId': '614987A8-FB6F-4604-95DF-D9A9081925CB', 'group': 'com.apple.ace.system', 'refId': 'HERE COMES THE REF ID', 'class': 'DomainObjectCreate'}
```

**Comment by danzatt** [comment]
So, I've finnaly solved it. Here's "plugin"  (sorry for dirty code):

``` python
#!/usr/bin/python
# -*- coding: utf-8 -*-

from plugin import *
from siriObjects.baseObjects import AceObject, ClientBoundCommand, ObjectIsCommand
from siriObjects.uiObjects import AddViews, AssistantUtteranceView
from siriObjects.emailObjects import *
from siriObjects.systemObjects import *
from siriObjects.contactObjects import PersonSearch, PersonSearchCompleted

class mail(Plugin):

    @register("en-US", ".*mail.*")  
    def mail(self, speech, language):      
      email = EmailEmail()
      email.subject = "test"
      email.type = "New"
      email.message = "testing"

      EmailDomain = DomainObjectCreate(self.refId, email)
      #print EmailDomain      
      answer = self.getResponseForRequest(EmailDomain)
      if ObjectIsCommand(answer, DomainObjectCreateCompleted):
    identifier = DomainObjectCreateCompleted(answer)
    print "\n\nIDENTIFIER : ", identifier.identifier
      else:
        raise StopPluginExecution("Unknown response: {0}".format(answer))

      #self.say("I've got identifer, displaying snippet ...", " ")

      EmailAce = Email()
      EmailAce.identifier = identifier.identifier

      EmailView = AddViews(self.refId, dialogPhase="Clarification")

      MyEmailSnippet = 0
      MyEmailSnippet = EmailSnippet()
      MyEmailSnippet.emails = [EmailAce]

      Spoken = AssistantUtteranceView()
      Spoken.text = "Creating snippet ..."

      EmailView.views = [Spoken, MyEmailSnippet]
      EmailView.scrollToTop = True
      self.sendRequestWithoutAnswer(EmailView)
      self.complete_request()
```

In emailObjects I've eddited :
in class EmailEmail the first line of **init** function : 

```
super(EmailEmail, self).__init__("com.apple.ace.email", None, "Email")
```

And I've also edited class Email, to support displaying Email snippets, just add :
to **init** function :

```
self.identifier = None # string
```

in to_plist function :

```
self.add_property('identifier')
```

**Comment by janrueth** [comment]
Just check out the newest commits and everything is already included.

Also identifier is not part of Email, just part of EmailEmail. Why don't you simply use the EmailEmail object which includes the identifier property?

  email = EmailEmail()
  email.subject = "test"
  email.recipientsTo = [personAttribute]
  email.type = "New"
  email.message = "testing"

  EmailDomain = DomainObjectCreate(self.refId, email)
  #print EmailDomain  
  answer = self.getResponseForRequest(EmailDomain)
  if ObjectIsCommand(answer, DomainObjectCreateCompleted):
identifier = DomainObjectCreateCompleted(answer)
print "\n\nIDENTIFIER : ", identifier.identifier
  else:
    raise StopPluginExecution("Unknown response: {0}".format(answer))

  #self.say("I've got identifer, displaying snippet ...", " ")

  email.identifier = identifier

  EmailView = AddViews(self.refId, dialogPhase="Clarification")

  MyEmailSnippet = 0
  MyEmailSnippet = EmailSnippet()
  MyEmailSnippet.emails = [email]

  Spoken = AssistantUtteranceView()
  Spoken.text = "Creating snippet ..."

  EmailView.views = [Spoken, MyEmailSnippet]
  EmailView.scrollToTop = True
  self.sendRequestWithoutAnswer(EmailView)
  self.complete_request()

**Comment by danzatt** [comment]
Thanks.

**Comment by janrueth** [comment]
Also I did some research, the Email object is a system object... I will move it to systemObjects
