### ISSUE TITLE
DomainObjectUpdate problem

### ISSUE THREAD

**Issue by danzatt** [janrueth/SiriServerCore#29]
Hi, I'm almost done with Email plugin but I need to ask user for email message and then update email DomainObject, but when I send DomainObjectUpdate Siri disconect from my server.
Original DomainObjectUpdate from 4S :

{"class"=>"DomainObjectUpdate",
 "properties"=>
  {"identifier"=>
    {"class"=>"Email",
     "properties"=>
      {"identifier"=>"amos://40EA282F-D883-42E8-B7FE-1C8D9026370D"},
     "group"=>"com.apple.ace.email"},
   "addFields"=>{"class"=>"Email", "group"=>"com.apple.ace.email"},
   "setFields"=>
    {"class"=>"Email",
     "properties"=>{"message"=>"This is a test"},
     "group"=>"com.apple.ace.email"},
   "removeFields"=>{"class"=>"Email", "group"=>"com.apple.ace.email"}},
 "aceId"=>"e1920529-9a04-4a84-9657-b12882382937",
 "refId"=>"E2E6F211-CD9D-42F7-B40C-1AB7FB7D67AC",
 "group"=>"com.apple.ace.system"}

My plugin is sending : 
{'properties': {'callbacks': [], 'removeFields': [], 'setFields': {'group': 'com.apple.ace.email', 'class': 'Email', 'properties': {'message': u'Hello'}}, 'identifier': {'group': 'com.apple.ace.email', 'class': 'Email', 'properties': {'identifier': 'amos://9660519B-805C-46C0-863E-CA869910A1D7'}}, 'addFields': {'group': 'com.apple.ace.email', 'class': 'Email', 'properties': {}}}, 'aceId': 'DD44D86D-765C-4663-A113-18EE51C11818', 'group': 'com.apple.ace.system', 'refId': 'E6EE6F82-F015-442B-B2D5-D9A9D4C3CB3A', 'class': 'DomainObjectUpdate'}

Here is plugin code :

http://pastebin.com/UEgyuyy4

**Comment by janrueth** [comment]
Oh yeah, I just see I did a mistake there, I added arrays instead of objects... will fix that asap

**Comment by janrueth** [comment]
I just pushed an update, it should work now
