### ISSUE TITLE
reminderObject possibly missing some arguments?

### ISSUE THREAD

**Issue by RedHaze** [janrueth/SiriServerCore#30]
When utilizing all of the current arguments in the reminderObject, a crash occurs on the springboard. Either my code is just poorly written or maybe something is missing? Below I have attached a log of siriproxy level 9 debug when creating a reminder with a confirmation and a cancellation. Hope this is fixed soon!

Confirmation:
http://pastebin.com/NjUveZTA

Cancellation:
http://pastebin.com/KMdn66Nu

**Comment by janrueth** [comment]
I have completly reworked the reminder objects, at lot was missing there and false, the names changed slightly. Have a look at siriObjects.reminderObjects
