### ISSUE TITLE
Cant run SiriServer - errors when making certs.

### ISSUE THREAD

**Issue by eugeene** [janrueth/SiriServerCore#31]
Hi, Im having issues when running the server for the first time, the error I get is:

3ugeene@Joshua:~/SiriServerCore$ python SiriServer.py 

I could not find valid certificates. I will now guide you through the process of creating some.
I will create a Certification Authority (CA) first
I successfully created a CA for you, will now use it to create SSL certificates.
We need to set the correct address of this machine in the certificate.
I will now query your system for its name. But it might be that you want to use a DNS name I cannot find.

-------- IMPORTANT ----------
Your system tells me that your hostname/IP is: Joshua.local
Do you want to use this information (y/n): y

------------ IMPORTANT ------------

All certificates have been generated... You must now install the CA certificate on your device

The file is located at keys/ca.pem in your SiriServer root

Make sure to uninstall an old CA certificate first"

THE CERTIFICATES MUST MATCH! IF YOU DID THIS HERE BEFORE, THE OLD ca.pem WON'T WORK ANYMORE

You can just EMail the keys/ca.pem file to yourself

INFO Starting server on port 4443
INFO Loading Session Certificates
Traceback (most recent call last):
  File "SiriServer.py", line 232, in <module>
    main()
  File "SiriServer.py", line 227, in main
    reactor.listenSSL(options.port, SiriFactory(), ssl.DefaultOpenSSLContextFactory(SERVER_KEY_FILE, SERVER_CERT_FILE))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/posixbase.py", line 444, in listenSSL
    p.startListening()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/tcp.py", line 877, in startListening
    self.factory.doStart()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/protocol.py", line 45, in doStart
    self.startFactory()
  File "SiriServer.py", line 56, in startFactory
    caFile = open("keys/SessionCACert.pem")
IOError: [Errno 2] No such file or directory: 'keys/SessionCACert.pem'

everything should be installed ok. I am using OS X 10.7 and python 2.7

**Comment by janrueth** [comment]
You obviously do not have the SessionCACert.pem, this is not generated by the script, you must copy it from the github sources

**Comment by eugeene** [comment]
yes, thank you! and sorry for this trivial problem. I accidentaly removed all files in keys dir.  Thank you!
