### ISSUE TITLE
To many open Files

### ISSUE THREAD

**Issue by jimmykane** [janrueth/SiriServerCore#34]
For some reason the flac encoder doesn't close all the file descriptors. Even though I have set the max number of files via ulimit to 60.000 the server crashes on that. That must indicate that somehow the flac encoder doesn't close the temporary file descriptors. 

Will post output soon!

**Comment by janrueth** [comment]
oh hm thats odd... I'll have a look into that

**Comment by janrueth** [comment]
sadly I was never able to get it to do everything in memory, the library was always stalling when trying to create a stream

**Comment by janrueth** [comment]
I did some research, I can confirm that the file is closed after a finish speech, but not if the speech is abortes, I already fixed this locally. Will push that during the day

**Comment by janrueth** [comment]
Pushed the fix
