### ISSUE TITLE
error on websearch

### ISSUE THREAD

**Issue by jimmykane** [janrueth/SiriServerCore#36]
INFO Best matching result: "^webSearchQuery^=^Either^^webSearchConfirmation^=^Yes^" with a confidence of 100.0%
ERROR Connection Lost: [Failure instance: Traceback: <class 'OpenSSL.SSL.SysCallError'>: (0, 'Error')
/usr/lib64/python2.7/site-packages/twisted/python/context.py:81:callWithContext
/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py:581:_doReadOrWrite
/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py:199:doRead
/usr/lib64/python2.7/site-packages/twisted/protocols/tls.py:413:dataReceived
--- <exception caught here> ---
/usr/lib64/python2.7/site-packages/twisted/protocols/tls.py:352:_flushReceiveBIO
]

**Comment by jimmykane** [comment]
I am just posting errors because I dont have the time to look at them before the next week :-(

**Comment by janrueth** [comment]
looks like the connection was just lost

**Comment by LowKey88** [comment]
yeah, seems got issue with websearch , it's not open safari.app, just saying "^webSearchQuery^=^Google^^webSearchConfirmation^=^Yes^"

INFO Best matching result: "Google" with a confidence of 84.8%
INFO Best matching result: "^webSearchQuery^=^Google^^webSearchConfirmation^=^Yes^" with a confidence of 100.0%

**Comment by janrueth** [comment]
will look into that

**Comment by janrueth** [comment]
it seems like you all don't have the startRequestHandler plugin activated, which handels these kinds of requests.

Add it as first priority to plugins.conf

**Comment by jimmykane** [comment]
Let me check.

**Comment by jimmykane** [comment]
My plugin is on!

**Comment by janrueth** [comment]
Do you use the one provided in this repo? I just tested it and it worked fine
