### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by ids-dev** [janrueth/SiriServerCore#38]
hi there my device connects but i keep getting a segmentation fault please view my log below

root@core:~/core# python SiriServer.py --port 443 -l debug
INFO Starting server on port 443
INFO Loading Session Certificates
INFO Setting Up Database
INFO Connection to Database
INFO Loading Plugin Framework
ERROR Plugin loading failed
Traceback (most recent call last):
  File "/root/core/PluginManager.py", line 30, in load_plugins
    **import**(pluginPath+"."+line,  globals(), locals(), [], -1)
  File "/root/core/plugins/WhoAmI/**init**.py", line 19
     def mePerson(self, speech, language):
    ^
 IndentationError: unexpected indent
INFO Server is running and listening for connections
INFO New connection from 94.14.96.35 on port 50148
INFO Currently 1 clients connected
DEBUG --------------HEADER START---------------
DEBUG ACE /ace HTTP/1.0

Host: core.siri-server.co.uk

User-Agent: Assistant(iPhone/iPhone2,1; iPhone OS/5.0.1/9A405) Ace/1.0

Content-Length: 2000000000

DEBUG ---------------HEADER END----------------
DEBUG Got packet with class: CreateSessionInfoRequest
DEBUG packet with content:
{'aceId': '10EEEB3D-236A-411A-9401-B7082E87C94B',
 'class': 'CreateSessionInfoRequest',
 'group': 'com.apple.ace.system',
 'properties': {'sessionInfoRequest': '\x01\x08K,\x91H\x1d\x9b}\xa01\x93\x0b\x88|\x111\xea~M\xcf\xe2\xcc\xfe\xc5\xdd\xe8\xc8F\x0e.\xb7\x15\xa2\xe0\xc1\x94y\x89\x12\x0c\x1d\x94\xbc\xb1\xa0\x1d&^\xa4|N==\xf0\x03\xfc\x8b\x8f\x8e\x9e\xcdn\x11\x15\xf1\xa8\tZ\x1b\xf0\xf9\r\xb3\x86`u-\xd0\xb6\xf6\xbf\xf3M:\x0fz\xc7#\xa2\x87\x03\x13\x991\xe2\xd9\xeb\x10E"&@\xfb\xe2\x9b\'\x15yQ\xa2\xcd\xc8\x9e-\xc2\xa9L\xf9\x18\x98\r\xdbC\x1b\xdd\xe7\xee\xe1%\xc95\xf5\xdd;\xc3\xfc\xeasD\xb8_\x9a\x9dL\xf4\x93\xd8\x8c\x0c\xd4\xe7\xb4\xea\xf1\x9a\x84\x9a##\xa3\xc2\x0f\xd3\xe7SM\xa0\x02l\xfd\\x93A\x98\xc9\xf0\xba\xa1\xa3,\xd2=\x02\x0f\xb5\x93jq:(\x18\x06b\xbe3_2\xcd\xed\x83;E\xc7\x1a\n\x98\xed\xbf\xfc[\xaa\x80\xe0-\xa3t\xc4\x9b\x9f\xb2\xee>\xf3\xf3T\xd6k\xd6\x9f\xcd\x8fI\xf1o\x05A2\x9c\x83\n\x7f\x06N\x9d?FvUFCI\xad\x82\x93\xedv\xd3\x8a\x125&\x00\x05\xccj\x11X=\x93\x1c\xab\xeb\xe0\x1f\x9a\xcb\xf6c\xecF\xe1\x00\x00\x00 \x00\x9a\xc41-\xe0)Vo\xe7\xca\xa7]\xae\x99\x10\xfa_\'\x9b6\x11\x19\\x8bh\x94\x1f\xb9\x8c\xad\xb3\x9b|\xbaF\xcb\x84~\x1d\xd0\x8b\xd1I\x7frQ\xd0\x14\xf7\x97\xd5'}}
DEBUG Sending packet with class: CommandFailed
DEBUG packet with content:
{'aceId': 'BF72B6CD-7BDA-4310-896B-3147E0CBB466',
 'class': 'CommandFailed',
 'group': 'com.apple.ace.system',
 'properties': {'callbacks': [],
                'errorCode': 0,
                'reason': 'Not authenticated'},
 'refId': '10EEEB3D-236A-411A-9401-B7082E87C94B'}
DEBUG Got packet with class: LoadAssistant
DEBUG packet with content:
{'aceId': 'D4548743-863B-44A1-ACEA-045EA6F21EE2',
 'class': 'LoadAssistant',
 'group': 'com.apple.ace.system',
 'properties': {'assistantId': 'EE3203B4-853C-488F-84EF-56CE33DD1D59',
                'speechId': 'edc6da91-529b-4354-b187-11c1f92fc4c2'}}
DEBUG Sending packet with class: AssistantLoaded
DEBUG packet with content:
{'aceId': 'ab0cbcf2-bd27-4500-804d-a31e1243e6c0',
 'class': 'AssistantLoaded',
 'group': 'com.apple.ace.system',
 'properties': {'dataAnchor': 'removed',
                'requestSync': False,
                'version': '20111216-32234-branches/telluride?cnxn=293552c2-8e11-4920-9131-5f5651ce244e'},
 'refId': 'D4548743-863B-44A1-ACEA-045EA6F21EE2'}
DEBUG Got packet with class: SetRestrictions
DEBUG packet with content:
{'aceId': '115EA9FB-D28C-40C7-B129-76ED5ACDD758',
 'class': 'SetRestrictions',
 'group': 'com.apple.ace.system'}
DEBUG Got packet with class: SetRestrictions
DEBUG packet with content:
{'aceId': '74AF9886-0441-4368-AA38-D3C4057478BC',
 'class': 'SetRestrictions',
 'group': 'com.apple.ace.system'}
DEBUG Got packet with class: ClearContext
DEBUG packet with content:
{'aceId': '90408776-0DED-496E-BA16-3D54605AA8C0',
 'class': 'ClearContext',
 'group': 'com.apple.ace.system'}
DEBUG Got packet with class: GetAnchors
DEBUG packet with content:
{'aceId': '27293234-E5F7-4CAC-8181-E7988D26E4A1',
 'class': 'GetAnchors',
 'group': 'com.apple.ace.sync',
 'properties': {'sources': ['com.apple.contact.people',
                            'com.apple.media.entities',
                            'com.apple.alarm.label',
                            'com.apple.reminder.list.name']}}
DEBUG Got packet with class: CancelSpeech
DEBUG packet with content:
{'aceId': '1587BA02-DF90-421D-BDDE-99618F1A1261',
 'class': 'CancelSpeech',
 'group': 'com.apple.ace.speech',
 'refId': '5C192B2E-18B0-4809-8CE9-AB859D303712'}
DEBUG Got packet with class: SetAlertContext
DEBUG packet with content:
{'aceId': 'ABB7EC3F-3E73-4489-B954-A5480592E374',
 'class': 'SetAlertContext',
 'group': 'com.apple.ace.system',
 'properties': {'context': [{'class': 'Sms',
                             'group': 'com.apple.ace.sms',
                             'properties': {'dateSent': datetime.datetime(2012, 3, 26, 15, 11, 37),
                                            'identifier': 'x-apple-sms:guid=10625',
                                            'msgSender': {'class': 'PersonAttribute',
                                                          'group': 'com.apple.ace.system',
                                                          'properties': {'data': '+NUMBER HERE',
                                                                         'displayText': 'NAME HERE',
                                                                         'object': {'class': 'Person',
                                                                                    'group': 'com.apple.ace.system',
                                                                                    'properties': {'firstName': 'NAME',
                                                                                                   'fullName': 'NAME',
                                                                                                   'lastName': 'NAME',
                                                                                                   'phones': [{'class': 'Phone',
                                                                                                               'group': 'com.apple.ace.system',
                                                                                                               'properties': {'number': '+447411656765'}}]}}}},
                                            'outgoing': False}}]}}
DEBUG Got packet with class: SetAlertContext
DEBUG packet with content:
{'aceId': 'A77A86C7-67FF-4F0F-BD36-FF2A6F5D9464',
 'class': 'SetAlertContext',
 'group': 'com.apple.ace.system',
 'properties': {'context': [{'class': 'Sms',
                             'group': 'com.apple.ace.sms',
                             'properties': {'dateSent': datetime.datetime(2012, 3, 26, 15, 22, 23),
                                            'identifier': 'x-apple-sms:guid=10626',
                                            'msgSender': {'class': 'PersonAttribute',
                                                          'group': 'com.apple.ace.system',
                                                          'properties': {'data': '86444',
                                                                         'displayText': '864 44',
                                                                         'object': {'class': 'Person',
                                                                                    'group': 'com.apple.ace.system',
                                                                                    'properties': {'phones': [{'class': 'Phone',
                                                                                                               'group': 'com.apple.ace.system',
                                                                                                               'properties': {'number': '86444'}}]}}}},
                                            'outgoing': False}},
                            {'class': 'Sms',
                             'group': 'com.apple.ace.sms',
                             'properties': {'dateSent': datetime.datetime(2012, 3, 26, 15, 11, 37),
                                            'identifier': 'x-apple-sms:guid=10625',
                                            'msgSender': {'class': 'PersonAttribute',
                                                          'group': 'com.apple.ace.system',
                                                          'properties': {'data': '+NUMBER',
                                                                         'displayText': 'NAME',
                                                                         'object': {'class': 'Person',
                                                                                    'group': 'com.apple.ace.system',
                                                                                    'properties': {'firstName': 'NAME',
                                                                                                   'fullName': 'NAME',
                                                                                                   'lastName': 'NAME',
                                                                                                   'phones': [{'class': 'Phone',
                                                                                                               'group': 'com.apple.ace.system',
                                                                                                               'properties': {'number': '+447411656765'}}]}}}},
                                            'outgoing': False}}]}}
DEBUG Got packet with class: StartSpeechRequest
DEBUG packet with content:
{'aceId': '4CF34C08-EF56-4FB4-8D1D-B2DD9DBD7288',
 'class': 'StartSpeechRequest',
 'group': 'com.apple.ace.speech',
 'properties': {'audioSource': 'BuiltInMic',
                'codec': 'Speex_WB_Quality8',
                'handsFree': False}}
DEBUG New start of speech received
DEBUG Got packet with class: SetRequestOrigin
DEBUG packet with content:
{'aceId': 'FF3EBC7B-B7CA-4D19-BA5B-BE8F90FCE2B2',
 'class': 'SetRequestOrigin',
 'group': 'com.apple.ace.system',
 'properties': {'age': 7984,
                'altitude': 152.91651916503906,
                'direction': -1.0,
                'horizontalAccuracy': 65.0,
                'latitude': 53.711410131560989,
                'longitude': -1.7292625554593315,
                'speed': -1.0,
                'verticalAccuracy': 10.0},
 'refId': '4CF34C08-EF56-4FB4-8D1D-B2DD9DBD7288'}
DEBUG Got packet with class: SpeechPacket
DEBUG packet with content:
{'aceId': '2FC08E1F-74BC-477A-A694-5150CD3776D2',
 'class': 'SpeechPacket',
 'group': 'com.apple.ace.speech',
 'properties': {'packetNumber': 0,
                'packets': ["\t\xd6f\x18\x0f\xf2w\xe6)\x04\x1b\xb8\x0b8#\xe6\xed\x84\x12\x88'|\x88@G\xc9\xdf\xa4b\x10N\xf70@\x8f\x9b\x9c#\x0c\xe0\x9dfsA\x1f'~\xc5\x9c\xe1;\xdet\x82>N\xd0\xc4\x18\x83t\xe1M\x04|\x9cx\xc8S\x04\xe0U\x9c\x08\xf9;\xf3\x98\xe8\r\xdbt\x8c\x11\xf2w\xe7BP\x1b\x9c \x00#\xe4\xef\xc6\x82\x15"]},
 'refId': '4CF34C08-EF56-4FB4-8D1D-B2DD9DBD7288'}
DEBUG Decoding speech packet
Segmentation fault
root@core:~/core# 

Thanks

**Comment by ids-dev** [comment]
as you can  see its picking up sms and a contact but i dunno why also thanks

**Comment by janrueth** [comment]
I guess you are using linux with a wrong version of libspeex optimized for mmx which won't work. review the README.md a solution is presented there, if it fixes your problem please close the issue

**Comment by ids-dev** [comment]
thanks ill try that, ill keep you updated

**Comment by ids-dev** [comment]
hi there again im on debian and i have run

sudo apt-get install libspeex1 libflac8

but this still seems to not have solved my issue

thanks

**Comment by janrueth** [comment]
yeah but did you look after the mmx version of libspeex which is probably installed and prefered?

**Comment by ids-dev** [comment]
ill will dig out my bash log and see which command i ran to finally make it work lol

thanks
