### ISSUE TITLE
ssl handshake failure (yes, another one, but I can't fix it)

### ISSUE THREAD

**Issue by gfarrell** [janrueth/SiriServerCore#41]
I used `sudo python SiriServer.py --port 443` to generate certificates, and installed `ca.pem` on my phone. I even deleted any other siri related certificate from my phone.

I still cannot get past this `ssl handshake failure`...

**Comment by janrueth** [comment]
did you try the diagnostic commands from the README.md?

**Comment by gfarrell** [comment]
This is what I get if I test with a basis server:

```
gideon@Plato:/var/Siri$ sudo openssl s_server -cert keys/server.crt -key keys/server.key -accept 443 -state
Using default temp DH parameters
Using default temp ECDH parameters
ACCEPT
SSL_accept:before/accept initialization
SSL_accept:SSLv3 read client hello A
SSL_accept:SSLv3 write server hello A
SSL_accept:SSLv3 write certificate A
SSL_accept:SSLv3 write server done A
SSL_accept:SSLv3 flush data
SSL_accept:failed in SSLv3 read client certificate A
ERROR
shutting down SSL
CONNECTION CLOSED
```

But my certificate  seems ok if I test it using `openssl s_client`. The reason I'm using 443 is because my previous SiriServer was set up on 443 and so my router is configured that way. It shouldn't make a difference should it?

**Comment by janrueth** [comment]
no the port is not included in the certificate, it should not matter.

The host in spire must match the host you created the certificates for otherwise you will get the error you got above

**Comment by gfarrell** [comment]
Ok, got it working. It detected the hostname automatically but I didn't change it to the FQDN. Thanks.

**Comment by myusuf3** [comment]
@gfarrell I am getting the same issue what did you do to resolve it

**Comment by gfarrell** [comment]
I don't really remember, but above I've said it's to do with the fully qualified domain name being incorrectly configured: the FQDN must match the host name on the certificate.
