### ISSUE TITLE
CommandSucceeded object ?

### ISSUE THREAD

**Issue by danzatt** [janrueth/SiriServerCore#42]
I was looking for object CommandSucceeded, but I couldn't find it.
(Look like this)
{"class"=>"CommandSucceeded",
 "refId"=>"51a6a02a-79aa-4667-8711-a83540b5b649",
 "group"=>"com.apple.ace.system",
 "aceId"=>"63E75DC8-2912-4615-BA34-812849710863"}

So I've added it to systemObjects :

class CommandSucceeded(ServerBoundCommand):
    groupIdentifier = "com.apple.ace.system"
    classIdentifier = "CommandSucceeded"

```
def __init__(self, plist):
    super(CommandSucceeded, self).__init__(plist)
```

**Comment by janrueth** [comment]
Seems like it is missing, will add it

**Comment by janrueth** [comment]
just added all systemobjects
