### ISSUE TITLE
Problem with some plugins

### ISSUE THREAD

**Issue by francysuri** [janrueth/SiriServerCore#43]
ji, i have a problem with some plugins, they fail loading and returns this error:
(this example is for shortMessage plugin, i tried one by one all the plugins and i left the ones who haven't returned an error)

INFO Loading Plugin Framework
Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/**init**.py", line 776, in emit
    msg = self.format(record)
  File "/usr/lib/python2.6/logging/**init**.py", line 654, in format
    return fmt.format(record)
  File "/usr/lib/python2.6/logging/**init**.py", line 454, in format
    s = s + record.exc_text.decode(sys.getfilesystemencoding())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 287: ordinal not in range(128)
can you help me fix this? i can upload somewhere the plugin so that you can see if there are any errors

**Comment by janrueth** [comment]
I assume you did not download it correctly and screwed up the encoding, also this is the wrong issue bank, use the one in the plugins repository
