### ISSUE TITLE
How to use MPSearch

### ISSUE THREAD

**Issue by danzatt** [janrueth/SiriServerCore#44]
How can I use MPSearch object ? I've tryed

songName = "Test"
    self.say("Looking for \"{0}\" ...".format(songName))
    searchSong = MPSearch(self.refId)
    searchSong.searchValue = songName
    songSearch = self.getResponseForRequest(searchSong)
    if ObjectIsCommand(songSearch, MPSearchCompleted):
      print "{0}".format(songSearch)
    else:
      raise StopPluginExecution("Unknown response: {0}".format(songSearch))

But it always didn't find anything (song is in my device).

**Comment by Devil-of-Chaos** [comment]
def searchMusic(self,music):
        constraints = MPSearchConstraint()
        constraints.query = music
        constraints.searchProperties = ["Album", "Artist", "Composer", "Genre", "Title"]
        search = MPSearch(self.refId)
        search.constraints = [constraints]
        search.maxResults = 10
        search.searchProperties = ["Album", "Artist", "Composer", "Genre", "Title"]
        search.searchTypes =  ["Playlist", "Podcast", "Song"]
        search.searchValue = music
        answerObj = self.getResponseForRequest(search)
        if ObjectIsCommand(answerObj, MPSearchCompleted):
            answer = MPSearchCompleted(answerObj)
            return answer.results if answer.results != None else []
        else:
            raise StopPluginExecution("Unknown response: {0}".format(answerObj))
            return []

**Comment by danzatt** [comment]
Thank you very much. I have log from 4S but Guzzoni just sent Utterance view (Looking for name) and there wasn't any search plist/answer from device.
