### ISSUE TITLE
SSL Handshake Failure

### ISSUE THREAD

**Issue by nightops** [janrueth/SiriServerCore#45]
I've went through the documentation in the README and did not find any errors.  I deleted everything in my keys directory except the EXAMPLE files and the 2 "Session" PEM files.  I then re-ran "python SiriServer.py" using the default port of 4443, and checked that it is properly forwarded in my router and that my SiriServer is running the same IP as what I have forwarded to in my router.  I continually get the following error:

WARNING SSL related error
WARNING [('SSL routines', 'SSL3_READ_BYTES', 'ssl handshake failure')]

This all started when I updated to the newest version of code about 3 days ago.

**Comment by janrueth** [comment]
Did you install the ca.pem on your phone? (you must remove any other certificate that includes the same ip or domain)

**Comment by nightops** [comment]
Yup

**Comment by nightops** [comment]
I may end up trying to regenerate the certs to use just my local network and switch  my Spire settings to point to my network IP and try it internally just to rule out any external interference.

The only other thing that I can think of was there were some Ubuntu 11.10 updates that I applied recently, so I may try an apt-get update/install to see if there is anything still hanging around that is broken.

**Comment by nightops** [comment]
Did all updates and restarted...same error.  Is there a way to get more specific information about the error?  I tried "python SiriServer.py debug", but I don't see a log anywhere, and it doesn't appear to output additional information in the console.

**Comment by janrueth** [comment]
you must use -ldebug to get more info in the console

ssl handshake failure is always due to incorrect certificate,

do the ip/domain entered during cert generation match the ip/domain you enter in spire?

**Comment by nightops** [comment]
When it prompts me for the hostname, I enter my URL "siri.domain.com", and then I enter https://siri.domain.com:4443 in Spire...  Then I removed all Profiles on my iPhone, emailed myself the new ca.pem file, and installed it... No dice.

**Comment by teeters** [comment]
I had the same problem until I tried a giving SiriServer a numerical ip address as the hostname.

**Comment by nightops** [comment]
Dumped the current directory and re-cloned it.  Ran everything from scratch..appears to be good now.  Must have copied over an old PEM file somewhere..I guess.
