### ISSUE TITLE
Can only connect once?

### ISSUE THREAD

**Issue by teeters** [janrueth/SiriServerCore#46]
I am running SiriServer on my Macbook, and so far I haven't had any trouble connecting or authenticating with the server. However, as soon as I close Siri on my iPhone (or the connection times out) I cannot reconnect. I've tried restarting the server, but it doesn't help. Think this might be an SSL issue but I'm not seeing any error messages. Suggestions?

**Comment by teeters** [comment]
Update: was able to accept new connections after opening up the Python interpreter and running a Hello World.

**Comment by janrueth** [comment]
okay, thats odd, maybe python needed some initialization .... I don't know, but I guess this is resolved then.
