### ISSUE TITLE
accents blocks recognition

### ISSUE THREAD

**Issue by chesnel** [janrueth/SiriServerCore#48]
Hello,

To start I want to thank you for this great server siri. I see many uses as possible :) Otherwise I met a little trouble. I am French and I tried to create queries with accents and apparently it doesn't work :

``` python
 @register("fr-FR",".*Éteindre.*Lumière.*Salon.*")
```

Do you have an idea of ​​problem?

Encore merci pour votre superbe travail :)

**Comment by Devil-of-Chaos** [comment]
You have to add u like

@register("fr-FR", u"Lumière")

**Comment by janrueth** [comment]
you need to prefix (thank you python < 3.0) every string with an u if it contains non ascii characters. Also you must save the file as utf-8.

**Comment by chesnel** [comment]
Thank you very much it's work perfectly and sorry for my noob attitude in django :)
