### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Begall** [janrueth/SiriServerCore#55]
Using the latest version of SiriServerCore, I'm trying to look up the length of a number that is specified in the command. Previously, this worked with no problem. Now when I try it, I get this error: 

Traceback (most recent call last):
  File "/home/xbmc/Git/SiriServerCore/plugin.py", line 121, in run
    self.**method(self, self.__speech, self.__lang, self.__method.__dict**[**criteria_key**][self.__lang].match(self.__speech))
  File "/home/xbmc/Git/SiriServerCore/plugins/XBMC2.py", line 173, in specificepisode_command
    if len(matchedRegex.group('episodenumber')) > 1:
TypeError: object of type 'NoneType' has no len()

Any ideas?

**Comment by janrueth** [comment]
Looks to me that 'episodenumber' is None, so I guess your regex is not right

**Comment by Begall** [comment]
Yeah it was an error in the regex, my bad.
