### ISSUE TITLE
Cannot get Siri to work on my Iphone4, log posted.

### ISSUE THREAD

**Issue by barkeeper** [janrueth/SiriServerCore#58]
Hi there, Just bought the SiriServer Setup utility from Cydia but cannot get it to work. What am I doing wrong? I tried re-installing both Siriserver and Spire without luck, tried both with the "certificate" that was in the first version and without.

I also signed up for a few API websites to add them to the basic support.

Here is my log, all help would be greatly appreciated.

INFO Starting server on port 4443
WARNING Starting, as requested, without SSL, connections are not secured and can be altered and eavesdropped on from client to server
INFO Loading Session Certificates
INFO Setting Up Database
INFO Connection to Database
INFO Loading Plugin Framework
CRITICAL Failed loading plugin due to missing API key: 'Could not find API key for: googleemail. Please check your apiKeys.conf'
CRITICAL Failed loading plugin due to missing API key: 'Could not find API key for: bing. Please check your apiKeys.conf'
CRITICAL Failed loading plugin due to missing API key: 'Could not find API key for: sickbeard_host. Please check your apiKeys.conf'
CRITICAL Failed loading plugin due to missing API key: 'Could not find API key for: twitter_consumer_key. Please check your apiKeys.conf'
CRITICAL Failed loading plugin due to missing API key: 'Could not find API key for: yelp. Please check your apiKeys.conf'
CRITICAL Failed loading plugin due to missing API key: 'Could not find API key for: wundergrounds. Please check your apiKeys.conf'
CRITICAL Failed loading plugin due to missing API key: 'Could not find API key for: wordnik. Please check your apiKeys.conf'
CRITICAL Failed loading plugin due to missing API key: 'Could not find API key for: wolframalpha. Please check your apiKeys.conf'
INFO Server is running and listening for connections
INFO New connection from 127.0.0.1 on port 49156
INFO Currently 1 clients connected
WARNING Database error on fetching assistant
INFO Connection timed out
INFO Connection Closed: Connection was closed cleanly.
INFO Currently 0 clients connected
INFO New connection from 127.0.0.1 on port 49166
INFO Currently 1 clients connected
INFO Connection timed out
INFO Connection Closed: Connection was closed cleanly.
INFO Currently 0 clients connected
INFO New connection from 127.0.0.1 on port 49217
INFO Currently 1 clients connected
INFO Connection timed out
INFO Connection Closed: Connection was closed cleanly.
INFO Currently 0 clients connected
INFO New connection from 127.0.0.1 on port 49227
INFO Currently 1 clients connected
INFO Connection timed out
INFO Connection Closed: Connection was closed cleanly.
INFO Currently 0 clients connected
INFO New connection from 127.0.0.1 on port 49455
INFO Currently 1 clients connected
INFO Sending flac to google for recognition
INFO Best matching result: "Hello" with a confidence of 52.82%
INFO Connection timed out
INFO Connection Closed: Connection was closed cleanly.
INFO Currently 0 clients connected
INFO New connection from 127.0.0.1 on port 49466
INFO Currently 1 clients connected
INFO Sending flac to google for recognition
INFO Best matching result: "Hello" with a confidence of 82.42%
INFO Connection Closed: Connection was closed cleanly.
INFO Currently 0 clients connected
INFO New connection from 127.0.0.1 on port 49518
INFO Currently 1 clients connected
INFO Sending flac to google for recognition
INFO Best matching result: "Hello" with a confidence of 90.01%
INFO Connection timed out
INFO Connection Closed: Connection was closed cleanly.
INFO Currently 0 clients connected
INFO New connection from 127.0.0.1 on port 49569
INFO Currently 1 clients connected
INFO Connection timed out
INFO Connection Closed: Connection was closed cleanly.
INFO Currently 0 clients connected
INFO New connection from 127.0.0.1 on port 49679
INFO Currently 1 clients connected
INFO Sending flac to google for recognition
INFO Best matching result: "Wow" with a confidence of 67.98%
INFO Connection timed out
INFO Connection Closed: Connection was closed cleanly.
INFO Currently 0 clients connected
INFO New connection from 127.0.0.1 on port 49845
INFO Currently 1 clients connected
INFO Connection timed out
INFO Connection Closed: Connection was closed cleanly.
INFO Currently 0 clients connected

**Comment by janrueth** [comment]
looks to me like the server works perfect :), I recommend asking the cydia package developer on how to add api keys to the system, seems like you are missing a lot.

**Comment by barkeeper** [comment]
Dear Eichhoenchen,
Do I need to add all the Api's to be able to actually use the system? I was thinking that for extra addon kind of features I need to add the Api's but for regular "Hello Siri" kind of commands it would just parse through the google voice system.

In short :  Now my Siri is appearing to be loading, and nothing happens, I can wait forever.

Any ideas ?

**Comment by janrueth** [comment]
As I said, please contact the developer of the cydia app. The server just gives developers the ability to have language to parse for plugins, it does not contain any text processing, thats what plugins are for. It will just convert your spoken language to text using google and feed that into the plugin system being siri compatible, so yes, you need the api keys to make the plugins work
