### ISSUE TITLE
Hilfe

### ISSUE THREAD

**Issue by 12345phil6** [janrueth/SiriServerCore#6]
hi eichhoernchen,

könntest du ein Video oder ne Beschreibung für ganz Dumme machen wie man den Server aufzieht also eine Schritt-für-Schritt-Anleitung

danke im Voraus

**Comment by cytec** [comment]
Ne beschreibung is doch auf der Main Page in der Readme enthalten...
noch etwas "genauer" is es in der alten repo beschrieben...

**Comment by janrueth** [comment]
Nein, frag im forum nach ob das jemand machen kann. Es ist eigentlich auch nicht schwer. Aber wenn du die installation schon nicht hin bekommst, ist die frage ob du den rest packst
