### ISSUE TITLE
Cannot connect to my server

### ISSUE THREAD

**Issue by ghost** [janrueth/SiriServerCore#67]
Whatever i do, i cannot connect to my siri server. it is running in terminal, but my idevice wont connect, and the incoming connection will not show up on my server.
Also, another problem maybe that I am not sure which certificate to use in the 'keys' file in siriserver root file with my device to connect. which one am i supposed to used(these are all the certificates present in the 'keys' folder in siriserver root file):
ca.pem (with lock over it)
ca.pem-EXAMPLE (of course not this)
cakey.pem (with lock)
server.crt (with lock)
server.crt-EXAMPLE
server.key (with lock)
server.key-EXAMPLE
SessionCACert.pem
SessionCert.pem

Any help is much appreciated, and none of these worked to connect to my server, even if i tried them one at a time.
my server is 192.168.1.1 on my local wifi and i have that in spire. and yes it is https

Another thing, if i wanted to use my server somehere else (on 3g or other wifi), would i just put my ip address in followed by the server and port? Like this?: (ip in X's)
XX.XX.XX.XX:192.168.1.1:443

Thank You

**Comment by janrueth** [comment]
The default port is 4443 not 443, you cannot use such a naming scheme to connect via 3G, you must create a nat forwarding rule in your router that says, every traffic incoming from tcp port 4443 is redirected to 192.168.0.1.1:4443

The ca.pem must be on the device, you can simply delete the "*-Example" files. But if you connect via a public ip or via a private ip, the certificate must always match the ip, so it is probably better to use a dns name.. please visit the forums (link on readme on main page) to get more info about that

**Comment by ghost** [comment]
I have indeed done all of this. Still no luck. I have installed the right certificate, made sure there were no other certificates, and have done the forwarding and nat forwarding. i still can't even get it to work on my LAN for some reason. I have added as exception on my pc firewall. i start the server and no connections are detected.
And you are sure it is 192.168.0.1.1 for LAN? On your old server I used 192.168.1.1, but the setup for the certificates did not give me this option,so I assume it is 192.168.0.1.1 like you showed.
Before I get it to work outside of my LAN, I just want to get it to at least work on my LAN.
Still no luck anyhow. Any suggestions?
Thank you.

P.S. In my router forwarding I cannot do 192.168.0.1.1 because you fill in the blanks after 192.168.1._____
So I just forwarded it to the router assigned IP of my computer that the server is running on which is 192.168.1.X
Any other suggestions?

EDIT: Also, should I put my PC in DMZ to access it outside of LAN?

**Comment by ghost** [comment]
I am now able to connect to my server on LAN. It shows the incoming connection on terminal server. But, there is the SSL error. I tried you said on the main page by inputing:
openssl s_server -cert keys/server.crt -key keys/server.key -accept 4443 -state
i get this when i try my ipod to connect while this small SSL server is running:
Using default temp DH parameters
Using default temp ECDH parameters
ACCEPT
SSL_accept:before/accept initialization
SSL_accept:SSLv3 read client hello A
SSL_accept:SSLv3 write server hello A
SSL_accept:SSLv3 write certificate A
SSL_accept:SSLv3 write key exchange A
SSL_accept:SSLv3 write server done A
SSL_accept:SSLv3 flush data
SSL_accept:failed in SSLv3 read client certificate A
ERROR
shutting down SSL
CONNECTION CLOSED
ACCEPT

This is strange, because there are no other certificates installed and it is the only one named ca.pem in keys file. But when I install this certificate on my ipod, it is called: SiriServer Fake CA Certificate. This is weird, and it is not working. I tried your old server, and its certificate name is SiriServer (just that). It had the same issues the new one is having. The SSL error was picked up when i start the small test server, but it is the right certificate. Any suggestions?

**Comment by ghost** [comment]
PROBLEM SOLVED. re-made certificate and used same domain as my computer address that I am putting in Spire. 
thank you. issue closed.
