### ISSUE TITLE
Server shows error on start up !!!

### ISSUE THREAD

**Issue by Aaryans** [janrueth/SiriServerCore#7]
I have installed twisted but still I get the following error
./siriserver.py : line 1: try:: command not found
./siriserver.py : line 2: from:: command not found
./siriserver.py : line 3: from:: command not found
./siriserver.py : line 4: except:: command not found
Can`t find file You need top install the twisted python libraries....... etc etc

but I have installed twisted lib 12.0.0

What am I doing wrong ?

**Comment by cytec** [comment]
start it like this: "python siriServer.py" if u dont call python first it uses bash ;)

**Comment by janrueth** [comment]
actually it is now called "python SiriServer.py"  note the capital Siri

**Comment by cytec** [comment]
oh, your right... didn't see that

**Comment by janrueth** [comment]
also ^^ highly not code related... closing
