### ISSUE TITLE
How to add a button？

### ISSUE THREAD

**Issue by pengyoukun** [janrueth/SiriServerCore#85]
Hello,I'm one of your user.Can you tell me how to add a button to open an url in my plugin?Thans!

**Comment by danzatt** [comment]
Here you got

> url = "http://example.com"
> view = UIAddViews(self.refId)
> button = UIButton()
> button.text = u"I'm working link"
> link = UIOpenLink("")
> link.ref = url.replace("//","")
> button.commands = [link]
> view.views = [button]
> self.send_object(view)

**Comment by pengyoukun** [comment]
Thanks very much for your help

**Comment by gavros** [comment]
Hello. How would you open a url without a button? In short, this is what I'm trying to accomplish:

SiriProxy code:
   "

```
listen_for /siri turn on the living room lamp/i do

open(‘http://mywebsite.com/controlfiles/livingroom-on.php’)

say “Turning on your living room lamp”

request_completed

end"
```
