### ISSUE TITLE
Have any body got the plugin that can read the SMS?

### ISSUE THREAD

**Issue by pengyoukun** [janrueth/SiriServerCore#86]
Have any body got the plugin that can read the SMS?Reply soon ,Thanks

**Comment by ericyanush** [comment]
Seeing as how the original post I made got lost in the spam on the GRWH forums, I have uploaded it to my git.
Feel free to use, re-use, improve and modify as you wish.

Eric

https://github.com/ericyanush/SiriServerSMSPlugin

**Comment by pengyoukun** [comment]
Thanks very much

**Comment by freitas666** [comment]
This plugin dont work for me =( do you help-me?

**Comment by ericyanush** [comment]
The plugin requires the changes in this pull request: https://github.com/Eichhoernchen/SiriServerCore/pull/75
be made to your Siri Server.

**Comment by freitas666** [comment]
I'll try again!

**Comment by freitas666** [comment]
Follow the error>

messages/**init**.py", line 634, in checkNewMessages
    self.say(random.choice(responses['noNewMessages'][language]))
KeyError: 'noNewMessages'
DEBUG Sending packet with class: AddViews
DEBUG packet with content:
{'aceId': '88C210B0-44A1-48BB-9FA9-827E515310CA',
 'class': 'AddViews',
 'group': 'com.apple.ace.assistant',
 'properties': {'callbacks': [],
                'views': [{'class': 'AssistantUtteranceView',
                           'group': 'com.apple.ace.assistant',
                           'properties': {'speakableText': 'There was an error during the processing of your request!',
                                          'text': 'There was an error during the processing of your request!'}}]},
 'refId': '8D71D03B-6737-48F4-8FD0-C2F5A5FADB7E'}
DEBUG Sending packet with class: RequestCompleted
DEBUG packet with content:
{'aceId': '9344A361-DEB1-4B0C-81F5-4792A3A3D035',
 'class': 'RequestCompleted',
 'group': 'com.apple.ace.system',
 'properties': {'callbacks': []},
 'refId': '8D71D03B-6737-48F4-8FD0-C2F5A5FADB7E'}
DEBUG Got packet with class: GetAnchors
DEBUG packet with content:
{'aceId': 'DB357F32-B3ED-4B3A-A5F7-EFA217169A6B',
 'class': 'GetAnchors',
 'group': 'com.apple.ace.sync',
 'properties': {'sources': ['com.apple.contact.people',
                            'com.apple.media.entities',
                            'com.apple.alarm.label',
                            'com.apple.reminder.list.name']}}
INFO Connection timed out
INFO Connection Closed: Connection was closed cleanly.
INFO Currently 0 clients connected

**Comment by ericyanush** [comment]
What language are you using?

**Comment by freitas666** [comment]
i'm brazilian, my iphone pt-BR

**Comment by ericyanush** [comment]
I have only built en-US into the plugin, the error you are seeing is because it is looking for a language that isn't programmed in. You are more than welcome to translate the plugin, and make a pull request to merge your changes back in!

Good luck!

**Comment by freitas666** [comment]
So my friend let's fix this problem, and going beyond'll need help if ever have any problems ok?

**Comment by freitas666** [comment]
Hi I managed to fix the error that pointed and already translated into Portuguese but is not showing the new message, even after that change in the archives!!

Can you help me?

**Comment by freitas666** [comment]
I solved the problem :)

Tks all...
