### ISSUE TITLE
New Issues 

### ISSUE THREAD

**Issue by totoantonio** [janrueth/SiriServerCore#87]
Hi Eichh,
Hope you can help me with this.. Can't solve this one. This happened after my VPS changed my IP. I generated new keys but im still having issues...

 File "SiriServer.py", line 251, in <module>
    main()
  File "SiriServer.py", line 246, in main
    reactor.listenSSL(options.port, SiriFactory(options.maxConnections), ssl.DefaultOpenSSLContextFactory(SERVER_KEY_FILE, SERVER_CERT_FILE))
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 444, in listenSSL
    p.startListening()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 868, in startListening
    skt.listen(self.backlog)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by danzatt** [comment]
Server is already running on that port you must shut down it. You can use bash command :

> netstat -tulpn | grep :4443

(replace 4443 with your server's port) This will output you something like :

> tcp        0      0 0.0.0.0:4443            0.0.0.0:\*               LISTEN      6031/python

So there you can see 6031/python (you will have something else than 6031) it's PID of SiriServer's running instance. If you want to start another on the same port you must kill it. You can easily enter command :

> kill PID

(You must replace PID with PID of SiriServer - in my case 6031) And you are done. If you are too lazy or you can't understand this you can just restart your computer.

**Comment by janrueth** [comment]
I guess is resolved, closing
