### ISSUE TITLE
readd gen_certs

### ISSUE THREAD

**Issue by cytec** [janrueth/SiriServerCore#9]
Hi, 

Just thought about re adding the "old" gen_certs stuff may be usefull for some users... 

Afaik there are only Little changes needet for the names and folders.

**Comment by janrueth** [comment]
Hm I think that this repo should only contain the core code, no scripts or anything...

**Comment by cytec** [comment]
what about an link or something...
just because generating those certs is a little bit tricky for some not so "advanced" users.

**Comment by janrueth** [comment]
I agree, it is a pain in the ass, but I don't offer here a ready to use service, just code... So I don't think that I should care about every step involving setup. Providing such info will only generate more issues because people fail using them and so the focus on code here is lost

**Comment by janrueth** [comment]
Maybe I will add the support of certificate creation to the server itself

**Comment by cytec** [comment]
yeah your right more stuff is likely to generate more issues but the implemention to the server itself would be cool i think.

**Comment by janrueth** [comment]
Currently on it...
