### ISSUE TITLE
Make plugins require iOS Version (iOS 6 Specific Plugins?)

### ISSUE THREAD

**Issue by weinzach** [janrueth/SiriServerCore#95]
I have a server iOS 5 and 6 compatible and I want to make plugins to take advantage of the new UIObjects but only for iOS 6 devices. I know the device sends the version number to the server. Does anyone know how to do this? @Eichhoernchen

**Comment by janrueth** [comment]
Yeah this should work, one must filter the User-Agent from the http header... will have a look into this when I got free time

**Comment by weinzach** [comment]
Any updates on this issue?

**Comment by janrueth** [comment]
Just commited it.

Various version infos are available in a plugin via:

```
    self.connection.phoneVersion
    self.connection.protocolVersion
    self.connection.clientOSVersion
    self.connection.clientOSbuildNumber
```

these values default to:

```
    phoneVersion = "Unknown"
    protocolVersion = 0.0
    clientOSVersion = 0.0
    clientOSbuildNumber = "Unknown"
```

notice phoneVersion and clientOSbuildNumber being strings and the other two floats..

I'm thinking weather to allow plugins to define a version for each method in the @register, thoughts on that?

**Comment by weinzach** [comment]
It would be nice also if then statements work too.

**Comment by janrueth** [comment]
Well you can do if statements with the variables I described above

**Comment by rotastrain** [comment]
i think adding it to register would be a unnecessary hassel. A simple if block would be enough to modulate the function if wanted.

**Comment by janrueth** [comment]
I changed phoneVersion to deviceVersion, such that it is more compatible with the OS X version of Siri
